version: "3.9"

services:
  web:
    build: .
    container_name: vuln_php
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    entrypoint: ["/entrypoint.sh"]
    networks:
      - vulnnet

  db:
    image: mysql:5.7
    container_name: vuln_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vulnbank
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - vulnnet

volumes:
  dbdata:

networks:
  vulnnet:
